export const VALUE_INPUT = "VALUE_INPUT"
export const NEW_PAGE_NUMBER = "NEW_PAGE_NUMBER"
export const COUNT = "COUNT";
export const SELECT_COUNTRY = "SELECT_COUNTRY";
export const DELETE_COUNTRY = "DELETE_COUNTRY";
export const GET_FILTER_COUNTRY = "GET_FILTER_COUNTRY";